apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: renting
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: renting 
spec:
  ports:
    - port: 5432
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: renting
  clusterIP: None
