apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deluge
  namespace: seedbox
  labels:
    app.kubernetes.io/name: deluge
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
spec:
  serviceName: deluge
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deluge
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deluge
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/component: server
      annotations:
        backup.velero.io/backup-volumes: deluge-config
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: 'Europe/Paris'
        - name: DELUGE_LOGLEVEL
          value: error
        image: linuxserver/deluge
        name: deluge
        ports:
        - containerPort: 8112
        resources:
          resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "700Mi"
        volumeMounts:
        - mountPath: /config
          name: deluge-config
        - mountPath: /downloads
          name: deluge-data-download
        - mountPath: /downloads/TV
          name: deluge-data-tv
        - mountPath: /downloads/Movies
          name: deluge-data-movies
      restartPolicy: Always
      volumes:
      - name: deluge-config
        persistentVolumeClaim:
          claimName: pvc-deluge
          readOnly: false
      - name: deluge-data-download
        persistentVolumeClaim:
          claimName: pvc-download
          readOnly: false
      - name: deluge-data-tv
        persistentVolumeClaim:
          claimName: pvc-tv
          readOnly: false
      - name: deluge-data-movies
        persistentVolumeClaim:
          claimName: pvc-movies
          readOnly: false
