apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: deluge
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
  name: deluge
  namespace: seedbox
spec:
  ports:
  - name: "8112"
    port: 8112
    targetPort: 8112
  - name: "tcp-deluge"
    port: 30305
    targetPort: 30305
    protocol: TCP
  - name: "udp-deluge"
    port: 30305
    targetPort: 30305
    protocol: UDP
  selector:
    app.kubernetes.io/name: deluge
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
status:
  loadBalancer: {}
