apiVersion: v1
kind: Namespace
metadata:
  name: matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: all
---
apiVersion: v1
kind: LimitRange
metadata:
  name: matomo-limit
  namespace: matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: all
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 100m
    defaultRequest:
      memory: 64Mi
      cpu: 50m
    max:
      memory: 512Mi
      cpu: 500m
    min:
      memory: 64Mi
      cpu: 50m
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: all
spec:
  hard:
    cpu: 0.5
    memory: 1Gi
    pods: "5"
    resourcequotas: "1"
    services: "3"
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: all
spec:
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-frontend-allow
  namespace: matomo
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: matomo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: matomo
      ports:
        - protocol: TCP
          port: 3306
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-allow-external
  namespace: matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: matomo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: matomo
  ingress:
  - ports:
    - port: 80
    from: []
