apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: matomo
  name: matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: matomo 
spec:
  serviceName: matomo
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: matomo 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: matomo
      annotations:
        backup.velero.io/backup-volumes: www-persistent-storage
    spec:
      containers:
      - image: matomo
        name: matomo
        env:
        - name: MATOMO_DATABASE_HOST
          value: matomo-mariadb
        - name: MATOMO_DATABASE_ADAPTER
          value: mysql
        - name: MATOMO_DATABASE_TABLES_PREFIX
          value: matomo
        - name: MATOMO_DATABASE_USERNAME
          value: root
        - name: MATOMO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root_password
        - name: MATOMO_DATABASE_DBNAME
          value: matomo
        ports:
        - containerPort: 80
          name: matomo
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"
        volumeMounts:
        - name: www-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: www-persistent-storage
        persistentVolumeClaim:
          claimName: matomo-data-pvc
