apiVersion: v1
kind: Service
metadata:
  name: matomo
  namespace: matomo
  labels:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: matomo 
spec:
  ports:
  - name: matomo
    protocol: TCP
    port: 80
  selector:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: matomo
