#cloud-config
hostname: ${hostname}
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $1$7IiAD+oL$x74MQltAZhAzAsa.xeVmG/
    ssh_authorized_keys:
      - ${public_ssh_key}
