apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
  name: radarr
  namespace: seedbox
spec:
  ports:
  - name: "7878"
    port: 7878
    targetPort: 7878
  selector:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
status:
  loadBalancer: {}
