apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bitwarden
  namespace: seedbox
  labels:
    app.kubernetes.io/name: bitwarden
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
