apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: bitwarden
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
  name: bitwarden
  namespace: seedbox
spec:
  serviceName: bitwarden
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitwarden
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitwarden
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/component: server
      annotations:
        backup.velero.io/backup-volumes: bitwarden-config
    spec:
      containers:
      - image: bitwardenrs/server
        name: bitwarden
        env:
        - name: ENABLE_DB_WAL
          value: "false"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "128Mi"
        volumeMounts:
        - mountPath: /data
          name: bitwarden-config
      restartPolicy: Always
      volumes:
      - name: bitwarden-config
        persistentVolumeClaim:
          claimName: pvc-bitwarden
          readOnly: false
