apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: bitwarden
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
  name: bitwarden
  namespace: seedbox
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: bitwarden
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
status:
  loadBalancer: {}
