---
- hosts: kubernetes
  remote_user: "ubuntu"
  become: yes

  tasks:
    # mount data /var/lib/rancher/k3s/storage -t 9p -o trans=virtio
    - name: Mount data
      mount:
        path: /var/lib/rancher/k3s/storage
        src: data
        fstype: 9p
        opts: trans=virtio
        state: mounted
