apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-renting-redis
  namespace: renting
  labels:
    name: pvc-renting-redis
spec:
  claimRef:
    name: pvc-renting-redis
    namespace: renting
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: data-renting-redis
    volumeAttributes:
      server: 192.168.0.11
      share: /mnt/projects/renting/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-renting-redis
  namespace: renting
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
