apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: renting
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: renting 
spec:
  ports:
    - port: 6379
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: renting
  clusterIP: None
