apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
  name: sonarr
  namespace: seedbox
spec:
  ports:
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
status:
  loadBalancer: {}
