apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-ombi
  namespace: seedbox
  labels:
    name: pvc-ombi
spec:
  claimRef:
    name: pvc-ombi
    namespace: seedbox
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: data-ombi
    volumeAttributes:
      server: 192.168.0.11
      share: /mnt/seedbox-config/ombi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ombi
  namespace: seedbox
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
