apiVersion: v1
kind: Service
metadata:
  namespace: seedbox
  labels:
    app.kubernetes.io/name: ombi
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
  name: ombi
spec:
  ports:
  - name: "3579"
    port: 3579
    targetPort: 3579
  selector:
    app.kubernetes.io/name: ombi
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: server
status:
  loadBalancer: {}