apiVersion: v1
kind: Service
metadata:
  namespace: renting
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: admin
    app.kubernetes.io/part-of: renting
  name: admin
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: admin
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: admin
    app.kubernetes.io/part-of: renting
status:
  loadBalancer: {}