---
- hosts: hypervisor
  remote_user: "{{ username }}"
  become: yes

  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Debian,codename=${distro_codename},label=Debian-Security' # security updates
        - 'o=Debian,codename=${distro_codename},label=Debian' # updates including non-security updates
        - 'o=Debian,codename=${distro_codename},a=proposed-updates'
      unattended_mail: 'dev.chateau@gmail.com'
    - role: stackhpc.libvirt-host

  tasks:
    # Install libvirt and cockpit
    - name: "Added security_driver none"
      lineinfile:
        path: /etc/libvirt/qemu.conf
        regexp: '^#security_driver = "selinux"'
        line: security_driver = "none"
    - name: Add user to group libvirt
      user:
        name: "{{ username }}"
        groups: libvirt
        append: yes
    - name: Install cockpit and bridge-utils
      apt:
        pkg:
        - cockpit
        - cockpit-machines
        - bridge-utils
    - name: Start and enabled service cockpit
      service:
        name: cockpit
        enabled: yes
        state: started
    
    # Get pfsense iso
    - name: Create a directory if it does not exist
      file:
        path:  /var/lib/libvirt/images/pfsense
        state: directory
        mode: '0755'
      tags:
        - pfsense
    - name: Download pfsense iso file
      get_url:
        url:  https://frafiles.pfsense.org/mirror/downloads/{{ pfsense_version }}.iso.gz
        dest: /var/lib/libvirt/images/pfsense/pfSense.iso.gz
      tags:
        - pfsense
    - name: Unarchive pfsense iso file
      command: gunzip pfSense.iso.gz
      args:
        chdir: /var/lib/libvirt/images/pfsense/
      tags:
        - pfsense

    # Set static ip address for br0
    - name: Copy interfaces file in /etc/network/interfaces
      template:
        src: hypervisor/interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
      vars:
        ip_address: "{{ br0_ip_address }}"
        ip_gateway: "{{ br0_ip_gateway }}"
    - name: Reboot
      reboot:
